### ISSUE TITLE
menu bug

### ISSUE THREAD

**Issue by YuriiHavryliuk** [MateAcademy-FE-July/headers-nov-team#14]
In styles .nav__item and .nav__link it is necessary to set explicitly to the second header

**Comment by witflash** [comment]
It seems to me in this case it doesn't affect on the project. Why is this a bug? 
There is another `.nav` element in the project and Sasha used it inside his own header :)
It will have been a bug if someone will use distinct `.nav` class in another header.

**Comment by YuriiHavryliuk** [comment]
You didn't understand. I in my styles indicated .nav__item and .nav__link. And my styles also applied to Sasha's header. It was necessary to specify .header-second .nav__item, etc. The bug is visible when mobile. I attached the screenshot. Errors I will correct.
![header2](https://user-images.githubusercontent.com/33283739/34354021-230cff5a-ea34-11e7-8269-f0cf512fe42f.JPG)
![header](https://user-images.githubusercontent.com/33283739/34354022-23282b68-ea34-11e7-8bdf-cf22c7f09057.JPG)

**Comment by witflash** [comment]
Oh, I understood. So create pull request and let fix this trouble :)

**Comment by YuriiHavryliuk** [comment]
ok :)

**Comment by Oleksandr58** [comment]
All good.
