### ISSUE TITLE
 Search goes outside the container

### ISSUE THREAD

**Issue by YuriiHavryliuk** [MateAcademy-FE-July/headers-nov-team#16]
When the screen size is reduced to 760 pixels, the "search"will climb out of the container. You did on flex and did not specify flex-flow: row wrap. I think this will solve the problem.
![image](https://user-images.githubusercontent.com/33283739/34355424-df98bef8-ea3d-11e7-873b-a1e178f43057.png)

**Comment by Oleksandr58** [comment]
Actual issue on 10.01.2018
