### ISSUE TITLE
Need fix behavior 3-th header when remote

### ISSUE THREAD

**Issue by Oleksandr58** [MateAcademy-FE-July/headers-nov-team#25]
All headers the same when remote without 3-th. Please fix this.
![image](https://user-images.githubusercontent.com/33155100/34768409-6a9d44ee-f603-11e7-8511-ab4e3429d931.png)
![image](https://user-images.githubusercontent.com/33155100/34768429-76b3708c-f603-11e7-8c75-ffdbf361cd69.png)

**Comment by witflash** [comment]
I'll repair this bug.

**Comment by witflash** [comment]
Done.
